#!/bin/bash

debug=0
while [ $# -gt 0 ]; do
       case "$1" in
      -h | --help )
              echo "Usage: $0 [-d 1-9] [-h]"
              exit 0
              ;;
      -d | --debug )
              if [[ "$2" =~ ^[1-9]$ ]]; then
                      debug="$2"
                      shift
                      echo "Debug mode ON, level $debug"
              else
                      echo "Cannot set debug without a debug level from 1 to 9" >&2
                      exit 2
              fi
              ;;
       * )
              echo "Usage: $0 [-d level] [-h]"
              echo "Argument '$1' not recognized" >&2
              exit 2
              ;; 
       esac
       shift
done
echo "Command line processing complete."
[  $debug ] && echo "Debug turned on and set to $debug."
# rest of script ...
