#!/bin/bash


debug=0
declare -a stuffToProcess
[ $# -gt 1 ] && echo "$# args left to process"

function usagehelp {
   echo "Usage: $0 [-d level] [-h]"
}


   while [ $# -gt 0 ]; do
         case "$1" in
         -h | --help )
              echo `usagehelp`
              exit 0
              ;;
         * )
              stuffToProcess+=("$1")
              ;;
              esac
              shift
done
[ ${#stuffToProcess[@]} ] && echo "Will do work on ${stuffToProcess[@]} (${#stuffToProcess[@]} items)"
