#!/bin/bash
# asks the user to guess a number from 1 to 10.
# 1. Begin by explaining to the user how the game works.
# 2. Generate a random number to be the correct answer and save it.
# 3. Repeatedly ask the user to guess your secret number. * Tell them if they have guessed more or less than the number.

scretnum=$(($RANDOM % 10 + 1))
read -p "I created a number between 1 to 10, you need to guess it by entering a number: " guess
if [ -n $guess ]; then
  echo $guess| grep -q '[^1-10]' && guess=0
  if [ $guess -lt 1 -o $guess -gt 10 ]; then
     echo "Your guess should be from 1 to 10 inclusive"
  else
     number=$guess
     if [ $number -eq $scretnum ]; then
        echo "Congratulation!! The secret number is $scretnum"
     elif [ $number -lt $scretnum ]; then
        echo "Sorry, your guess is less than the scret number $scretnum"
     elif [ $number -gt $scretnum ]; then
        echo "Sorry, your guess is greater than the scret number $scretnum"
     fi

  fi
fi
