#!/bin/bash

# Assign domain name to the variable "domains"
domains=(`ls -l|awk '{print $9}'`)
domainnum=${#domains[@]}

# show the system name
echo "System name is: `uname`"

# check if there is any domain in the system
case $domains in
    '(none)')
         echo "There is no domain in this system"
         exit 0
         ;;
    *)
         echo "There is $domainnum in this system, they are:"
         echo "${domains[@]}"
         ;;
    esac
